ALTER TYPE "InspectionPhotoType" ADD VALUE IF NOT EXISTS 'WHEEL_FRONT_LEFT';
ALTER TYPE "InspectionPhotoType" ADD VALUE IF NOT EXISTS 'WHEEL_FRONT_RIGHT';
ALTER TYPE "InspectionPhotoType" ADD VALUE IF NOT EXISTS 'WHEEL_REAR_LEFT';
ALTER TYPE "InspectionPhotoType" ADD VALUE IF NOT EXISTS 'WHEEL_REAR_RIGHT';
