import {
  Building2,
  FileText,
  Package,
  Zap,
  Ruler,
  Route,
  Paperclip,
} from "lucide-react";

export const FORM_STEPS = [
  {
    number: 1,
    title: "Datos del cliente",
    description: "Información de contacto",
    icon: Building2,
    color: "primary" as const,
    fields: [
      "razonSocial",
      "personaContacto",
      "email",
      "direccion",
      "localidad",
      "provinciaEstado",
      "pais",
      "codigoPostal",
      "website",
      "numeroIdentificacionFiscal",
      "distribuidor",
      "contactoDistribuidor",
      "fechaCierre",
    ],
  },
  {
    number: 2,
    title: "Descripción operación",
    description: "Detalles logísticos",
    icon: FileText,
    color: "blue" as const,
    fields: [
      "notasOperacion",
      "tieneRampas",
      "notasRampas",
      "tienePasosPuertas",
      "notasPasosPuertas",
      "tieneRestricciones",
      "notasRestricciones",
      "alturaMaximaNave",
      "anchoPasilloActual",
      "superficieTrabajo",
      "condicionesSuelo",
      "tipoOperacion",
    ],
  },
  {
    number: 3,
    title: "Datos aplicación",
    description: "Información técnica",
    icon: Package,
    color: "amber" as const,
    fields: [
      "descripcionProducto",
      "alturaUltimoNivelEstanteria",
      "maximaAlturaElevacion",
      "pesoCargaMaximaAltura",
      "pesoCargaPrimerNivel",
      "dimensionesAreaTrabajoAncho",
      "dimensionesAreaTrabajoFondo",
      "turnosTrabajo",
      "fechaEstimadaDefinicion",
      "alimentacionDeseada",
    ],
  },
  {
    number: 4,
    title: "Equipos eléctricos",
    description: "Especificaciones eléctricas",
    icon: Zap,
    color: "violet" as const,
    fields: ["equiposElectricos"],
  },
  {
    number: 5,
    title: "Dimensiones cargas",
    description: "Tabla de dimensiones",
    icon: Ruler,
    color: "emerald" as const,
    fields: ["dimensionesCargas"],
  },
  {
    number: 6,
    title: "Pasillo actual",
    description: "Medidas del pasillo",
    icon: Route,
    color: "rose" as const,
    fields: ["pasilloActual"],
  },
  {
    number: 7,
    title: "Archivos adjuntos",
    description: "Fotos, videos y documentos",
    icon: Paperclip,
    color: "cyan" as const,
    fields: ["archivos"],
  },
];
