import { FileText, Package, Zap, Ruler, Route, Paperclip } from "lucide-react";

// Steps optimizados: Se eliminó el Step de datos del cliente (autocompletado)
// El campo fechaCierre se movió al Step 1 (Descripción operación)
export const FORM_STEPS = [
  {
    number: 1,
    title: "Descripción operación",
    description: "Detalles logísticos",
    icon: FileText,
    color: "primary" as const,
    fields: [
      "fechaCierre",
      "notasOperacion",
      "tieneRampas",
      "notasRampas",
      "tienePasosPuertas",
      "notasPasosPuertas",
      "tieneRestricciones",
      "notasRestricciones",
      "alturaMaximaNave",
      "anchoPasilloActual",
      "superficieTrabajo",
      "condicionesSuelo",
      "tipoOperacion",
    ],
  },
  {
    number: 2,
    title: "Datos aplicación",
    description: "Información técnica",
    icon: Package,
    color: "blue" as const,
    fields: [
      "descripcionProducto",
      "alturaUltimoNivelEstanteria",
      "maximaAlturaElevacion",
      "pesoCargaMaximaAltura",
      "pesoCargaPrimerNivel",
      "dimensionesAreaTrabajoAncho",
      "dimensionesAreaTrabajoFondo",
      "turnosTrabajo",
      "fechaEstimadaDefinicion",
      "alimentacionDeseada",
    ],
  },
  {
    number: 3,
    title: "Equipos eléctricos",
    description: "Especificaciones eléctricas",
    icon: Zap,
    color: "amber" as const,
    fields: ["equiposElectricos"],
  },
  {
    number: 4,
    title: "Dimensiones cargas",
    description: "Tabla de dimensiones",
    icon: Ruler,
    color: "emerald" as const,
    fields: ["dimensionesCargas"],
  },
  {
    number: 5,
    title: "Pasillo actual",
    description: "Medidas del pasillo",
    icon: Route,
    color: "violet" as const,
    fields: ["pasilloActual"],
  },
  {
    number: 6,
    title: "Archivos adjuntos",
    description: "Fotos, videos y documentos",
    icon: Paperclip,
    color: "rose" as const,
    fields: ["archivos"],
  },
];
