import {
  Building2,
  FileText,
  Package,
  Zap,
  Ruler,
  Layout,
  Paperclip,
} from "lucide-react";

export const FORM_STEPS = [
  {
    number: 1,
    title: "Datos del Cliente",
    description: "Información de contacto",
    icon: Building2,
    color: "primary" as const,
    fields: [
      "razonSocial",
      "personaContacto",
      "email",
      "direccion",
      "localidad",
      "provinciaEstado",
      "pais",
      "codigoPostal",
      "website",
      "numeroIdentificacionFiscal",
      "distribuidor",
      "contactoDistribuidor",
      "fechaCierre",
    ],
  },
  {
    number: 2,
    title: "Descripción Operación",
    description: "Detalles de la operación",
    icon: FileText,
    color: "blue" as const,
    fields: ["notasOperacion"],
  },
  {
    number: 3,
    title: "Datos Aplicación",
    description: "Información técnica",
    icon: Package,
    color: "amber" as const,
    fields: [
      "descripcionProducto",
      "alturaUltimoNivelEstanteria",
      "maximaAlturaElevacion",
      "pesoCargaMaximaAltura",
      "pesoCargaPrimerNivel",
      "dimensionesAreaTrabajoAncho",
      "dimensionesAreaTrabajoFondo",
      "turnosTrabajo",
      "fechaEstimadaDefinicion",
      "alimentacionDeseada",
    ],
  },
  {
    number: 4,
    title: "Equipos Eléctricos",
    description: "Especificaciones eléctricas",
    icon: Zap,
    color: "violet" as const,
    fields: ["equiposElectricos"],
  },
  {
    number: 5,
    title: "Dimensiones Cargas",
    description: "Tabla de dimensiones",
    icon: Ruler,
    color: "emerald" as const,
    fields: ["dimensionesCargas"],
  },
  {
    number: 6,
    title: "Especificaciones Pasillo",
    description: "Medidas del pasillo",
    icon: Layout,
    color: "rose" as const,
    fields: ["especificacionesPasillo"],
  },
  {
    number: 7,
    title: "Archivos Adjuntos",
    description: "Fotos, videos y documentos",
    icon: Paperclip,
    color: "cyan" as const,
    fields: ["archivos"],
  },
];
