import { FileText, Package, Zap, Ruler, Layout, Paperclip } from "lucide-react";

export const FORM_STEPS = [
  {
    number: 1,
    title: "Descripción operación",
    shortTitle: "Descripción",
    description: "Detalles de la operación",
    icon: FileText,
    color: "blue" as const,
    fields: ["notasOperacion", "fechaCierre"],
  },
  {
    number: 2,
    title: "Datos aplicación",
    shortTitle: "Aplicación",
    description: "Información técnica",
    icon: Package,
    color: "amber" as const,
    fields: [
      "descripcionProducto",
      "alturaUltimoNivelEstanteria",
      "maximaAlturaElevacion",
      "pesoCargaMaximaAltura",
      "pesoCargaPrimerNivel",
      "dimensionesAreaTrabajoAncho",
      "dimensionesAreaTrabajoFondo",
      "turnosTrabajo",
      "fechaEstimadaDefinicion",
      "alimentacionDeseada",
    ],
  },
  {
    number: 3,
    title: "Equipos eléctricos",
    shortTitle: "Equipos",
    description: "Especificaciones eléctricas",
    icon: Zap,
    color: "violet" as const,
    fields: ["equiposElectricos"],
  },
  {
    number: 4,
    title: "Dimensiones cargas",
    shortTitle: "Dimensiones",
    description: "Tabla de dimensiones",
    icon: Ruler,
    color: "emerald" as const,
    fields: ["dimensionesCargas"],
  },
  {
    number: 5,
    title: "Especificaciones pasillo",
    shortTitle: "Especificaciones",
    description: "Medidas del pasillo",
    icon: Layout,
    color: "rose" as const,
    fields: ["especificacionesPasillo"],
  },
  {
    number: 6,
    title: "Archivos adjuntos",
    shortTitle: "Archivos",
    description: "Fotos, videos y documentos",
    icon: Paperclip,
    color: "cyan" as const,
    fields: ["archivos"],
  },
];
