import { FileText, Package, Zap, Ruler, Layout, Paperclip } from "lucide-react";

export const FORM_STEPS = [
  {
    number: 1,
    title: "forms.industrial.steps.operation.title",
    shortTitle: "forms.industrial.steps.operation.shortTitle",
    description: "forms.industrial.steps.operation.description",
    icon: FileText,
    color: "blue" as const,
    fields: ["notasOperacion", "fechaCierre"],
  },
  {
    number: 2,
    title: "forms.industrial.steps.application.title",
    shortTitle: "forms.industrial.steps.application.shortTitle",
    description: "forms.industrial.steps.application.description",
    icon: Package,
    color: "amber" as const,
    fields: [
      "descripcionProducto",
      "alturaUltimoNivelEstanteria",
      "maximaAlturaElevacion",
      "pesoCargaMaximaAltura",
      "pesoCargaPrimerNivel",
      "dimensionesAreaTrabajoAncho",
      "dimensionesAreaTrabajoFondo",
      "turnosTrabajo",
      "fechaEstimadaDefinicion",
      "alimentacionDeseada",
    ],
  },
  {
    number: 3,
    title: "forms.industrial.steps.batteries.title",
    shortTitle: "forms.industrial.steps.batteries.shortTitle",
    description: "forms.industrial.steps.batteries.description",
    icon: Zap,
    color: "violet" as const,
    fields: ["equiposElectricos"],
  },
  {
    number: 4,
    title: "forms.industrial.steps.loads.title",
    shortTitle: "forms.industrial.steps.loads.shortTitle",
    description: "forms.industrial.steps.loads.description",
    icon: Ruler,
    color: "emerald" as const,
    fields: ["dimensionesCargas"],
  },
  {
    number: 5,
    title: "forms.industrial.steps.aisle.title",
    shortTitle: "forms.industrial.steps.aisle.shortTitle",
    description: "forms.industrial.steps.aisle.description",
    icon: Layout,
    color: "rose" as const,
    fields: ["especificacionesPasillo"],
  },
  {
    number: 6,
    title: "forms.industrial.steps.files.title",
    shortTitle: "forms.industrial.steps.files.shortTitle",
    description: "forms.industrial.steps.files.description",
    icon: Paperclip,
    color: "cyan" as const,
    fields: ["archivos"],
  },
];
